version: "0.5"

processes:
  postgres-compose:
    command: nix run .#arion -L
    log_location: ./postgres.log
    log_configuration:
      disable_json: true
      no_metadata: true  
    readiness_probe:
      exec:
        command: pg_isready -h 127.0.0.1 -p 5432 -d default -U postgres
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 60
